---
# defaults/main.yml for elastic_backup_restore

# Target host
elastic_backup_restore_host: ""

# Authentication
elastic_backup_restore_username: ""
elastic_backup_restore_password: ""
elastic_backup_restore_api_key: ""

# Behavior
elastic_backup_restore_validate_certs: true
elastic_backup_restore_state: present
