---
# defaults/main.yml for elastic_monitoring

# Target host
elastic_monitoring_host: ""

# Authentication
elastic_monitoring_username: ""
elastic_monitoring_password: ""
elastic_monitoring_api_key: ""

# Behavior
elastic_monitoring_validate_certs: true
elastic_monitoring_state: present
