---
namespace: stevefulme1
name: elastic
version: 1.0.1
readme: README.md
authors:
  - Steve Fulmer <sfulmer@redhat.com>
description: Ansible collection for Elastic Stack (Elasticsearch, Kibana, Fleet) with EDA plugins
license_file: LICENSE
tags:
  - elasticsearch
  - kibana
  - elastic
  - eda
  - fleet
  - observability
  - logging
  - monitoring
dependencies: {}
repository: https://github.com/stevefulme1/ansible-elastic
documentation: https://github.com/stevefulme1/ansible-elastic
homepage: https://github.com/stevefulme1/ansible-elastic
issues: https://github.com/stevefulme1/ansible-elastic/issues
