---
argument_specs:
  main:
    short_description: "Manage index templates and mappings"
    options:
      elastic_index_template_management_host:
        description: Target host address
        type: str
        required: true
      elastic_index_template_management_username:
        description: Authentication username
        type: str
      elastic_index_template_management_password:
        description: Authentication password
        type: str
      elastic_index_template_management_api_key:
        description: API key for authentication
        type: str
      elastic_index_template_management_validate_certs:
        description: Validate SSL certificates
        type: bool
        default: true
      elastic_index_template_management_state:
        description: Desired state
        type: str
        default: present
        choices: [present, absent]
