---
# defaults/main.yml for elastic_cluster_setup

# Target host
elastic_cluster_setup_host: ""

# Authentication
elastic_cluster_setup_username: ""
elastic_cluster_setup_password: ""
elastic_cluster_setup_api_key: ""

# Behavior
elastic_cluster_setup_validate_certs: true
elastic_cluster_setup_state: present
