---
# defaults/main.yml for elastic_data_stream_setup

# Target host
elastic_data_stream_setup_host: ""

# Authentication
elastic_data_stream_setup_username: ""
elastic_data_stream_setup_password: ""
elastic_data_stream_setup_api_key: ""

# Behavior
elastic_data_stream_setup_validate_certs: true
elastic_data_stream_setup_state: present
