---
galaxy_info:
  author: Steve Fulmer
  description: "Enable TLS, authentication, and RBAC"
  license: Apache-2.0
  min_ansible_version: "2.16"
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - elastic
dependencies: []
