---
# defaults/main.yml for elastic_index_template_management

# Target host
elastic_index_template_management_host: ""

# Authentication
elastic_index_template_management_username: ""
elastic_index_template_management_password: ""
elastic_index_template_management_api_key: ""

# Behavior
elastic_index_template_management_validate_certs: true
elastic_index_template_management_state: present
