---
# defaults/main.yml for elastic_security_setup

# Target host
elastic_security_setup_host: ""

# Authentication
elastic_security_setup_username: ""
elastic_security_setup_password: ""
elastic_security_setup_api_key: ""

# Behavior
elastic_security_setup_validate_certs: true
elastic_security_setup_state: present
