#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Steve Fulmer (@stevefulme1)
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r"""
---
module: security_detection_rule
short_description: Manage Kibana Security detection rules
version_added: "1.0.0"
description:
  - Create, update, and delete Kibana Security SIEM detection rule resources.
  - Supports check mode and diff mode for safe operations.
author:
  - "Steve Fulmer (@stevefulme1)"
options:
  state:
    description:
      - Desired state of the detection rule resource.
    type: str
    choices: ['present', 'absent']
    default: present
  rule_id:
    description:
      - The internal UUID of the detection rule assigned by Elastic.
      - Required when updating or deleting an existing rule.
    type: str
  name:
    description:
      - The name of the detection rule.
    type: str
  description:
    description:
      - A description of what the detection rule detects.
    type: str
  risk_score:
    description:
      - The risk score for alerts generated by this rule, from 0 to 100.
    type: int
  severity:
    description:
      - The severity level for alerts generated by this rule.
    type: str
    choices: ['low', 'medium', 'high', 'critical']
  type:
    description:
      - The type of detection rule.
    type: str
    choices: ['query', 'saved_query', 'threshold', 'eql', 'machine_learning', 'threat_match', 'new_terms', 'esql']
  query:
    description:
      - The query string used by the rule to detect threats.
    type: str
  index:
    description:
      - A list of index patterns the rule queries.
    type: list
    elements: str
  interval:
    description:
      - How often the rule runs, specified as a time value string.
    type: str
    default: "5m"
  from_time:
    description:
      - The relative start time for the rule look-back window.
      - Maps to the C(from) field in the API payload.
    type: str
    default: "now-6m"
  to_time:
    description:
      - The relative end time for the rule look-back window.
      - Maps to the C(to) field in the API payload.
    type: str
    default: "now"
  language:
    description:
      - The query language used by the rule.
    type: str
    choices: ['kuery', 'lucene', 'eql', 'esql']
  enabled:
    description:
      - Whether the detection rule is enabled.
    type: bool
    default: true
  tags:
    description:
      - A list of tags to categorize the detection rule.
    type: list
    elements: str
    default: []
  filters:
    description:
      - A list of Elasticsearch filter objects applied to the rule query.
    type: list
    elements: dict
  threat:
    description:
      - A list of MITRE ATT&CK threat framework entries associated with the rule.
    type: list
    elements: dict
  actions:
    description:
      - A list of actions to execute when the rule generates an alert.
    type: list
    elements: dict
    default: []
extends_documentation_fragment:
  - stevefulme1.elastic.auth
"""

EXAMPLES = r"""
- name: Create a detection rule
  stevefulme1.elastic.security_detection_rule:
    name: "High CPU Alert"
    description: "Detects high CPU usage"
    risk_score: 50
    severity: "medium"
    type: "query"
    query: "host.cpu.usage > 90"
    index:
      - "metrics-*"
    interval: "5m"
    from_time: "now-6m"
    to_time: "now"
    language: "kuery"
    enabled: true
    tags:
      - production
    state: present

- name: Update a detection rule
  stevefulme1.elastic.security_detection_rule:
    rule_id: "existing-rule-id"
    name: "High CPU Alert"
    description: "Detects high CPU usage - updated"
    risk_score: 75
    severity: "high"
    type: "query"
    query: "host.cpu.usage > 80"
    index:
      - "metrics-*"
    state: present

- name: Delete a detection rule
  stevefulme1.elastic.security_detection_rule:
    rule_id: "existing-rule-id"
    state: absent
"""

RETURN = r"""
id:
  description: The internal UUID of the detection rule.
  returned: success
  type: str
name:
  description: The name of the detection rule.
  returned: success
  type: str
"""

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.stevefulme1.elastic.plugins.module_utils.api_client import (
    Client,
    ClientError,
    argument_spec as auth_argument_spec,
)


def get_current_state(client, module):
    """Retrieve the current state of a detection rule."""
    rule_id = module.params.get("rule_id")
    if rule_id is None:
        # Try to find by name in the list
        name = module.params.get("name")
        if name is None:
            return None
        try:
            response = client.get("/api/detection_engine/rules/_find")
            items = response.get("data", [])
            for item in items:
                if item.get("name") == name:
                    return item
            return None
        except ClientError:
            return None

    try:
        response = client.get(
            "/api/detection_engine/rules",
            params={"id": rule_id},
        )
        if isinstance(response, dict) and response.get("id"):
            return response
        return None
    except ClientError:
        return None


def needs_update(current, desired):
    """Compare current state against desired params and return True if an update is needed."""
    if current is None:
        return True
    for key, value in desired.items():
        if value is None:
            continue
        current_value = current.get(key)
        if current_value != value:
            return True
    return False


def build_payload(module, for_update=False):
    """Build the API request payload from module params."""
    payload = {}

    if module.params.get("name") is not None:
        payload["name"] = module.params["name"]

    if module.params.get("description") is not None:
        payload["description"] = module.params["description"]

    if module.params.get("risk_score") is not None:
        payload["risk_score"] = module.params["risk_score"]

    if module.params.get("severity") is not None:
        payload["severity"] = module.params["severity"]

    if module.params.get("type") is not None:
        payload["type"] = module.params["type"]

    if module.params.get("query") is not None:
        payload["query"] = module.params["query"]

    if module.params.get("index") is not None:
        payload["index"] = module.params["index"]

    if module.params.get("interval") is not None:
        payload["interval"] = module.params["interval"]

    # Map from_time -> from and to_time -> to (from is a Python keyword)
    if module.params.get("from_time") is not None:
        payload["from"] = module.params["from_time"]

    if module.params.get("to_time") is not None:
        payload["to"] = module.params["to_time"]

    if module.params.get("language") is not None:
        payload["language"] = module.params["language"]

    if module.params.get("enabled") is not None:
        payload["enabled"] = module.params["enabled"]

    if module.params.get("tags") is not None:
        payload["tags"] = module.params["tags"]

    if module.params.get("filters") is not None:
        payload["filters"] = module.params["filters"]

    if module.params.get("threat") is not None:
        payload["threat"] = module.params["threat"]

    if module.params.get("actions") is not None:
        payload["actions"] = module.params["actions"]

    return payload


def main():
    spec = auth_argument_spec()
    spec.update(
        dict(
            state=dict(type="str", choices=["present", "absent"], default="present"),

            rule_id=dict(
                type="str",
            ),

            name=dict(
                type="str",
            ),

            description=dict(
                type="str",
            ),

            risk_score=dict(
                type="int",
            ),

            severity=dict(
                type="str",
                choices=["low", "medium", "high", "critical"],
            ),

            type=dict(
                type="str",
                choices=[
                    "query", "saved_query", "threshold", "eql",
                    "machine_learning", "threat_match", "new_terms", "esql",
                ],
            ),

            query=dict(
                type="str",
            ),

            index=dict(
                type="list",
                elements="str",
            ),

            interval=dict(
                type="str",
                default="5m",
            ),

            from_time=dict(
                type="str",
                default="now-6m",
            ),

            to_time=dict(
                type="str",
                default="now",
            ),

            language=dict(
                type="str",
                choices=["kuery", "lucene", "eql", "esql"],
            ),

            enabled=dict(
                type="bool",
                default=True,
            ),

            tags=dict(
                type="list",
                elements="str",
                default=[],
            ),

            filters=dict(
                type="list",
                elements="dict",
            ),

            threat=dict(
                type="list",
                elements="dict",
            ),

            actions=dict(
                type="list",
                elements="dict",
                default=[],
            ),
        )
    )

    module = AnsibleModule(
        argument_spec=spec,
        supports_check_mode=True,
    )

    state = module.params["state"]
    result = dict(changed=False, diff=dict(before={}, after={}))

    try:
        client = Client(module)
        client.headers["kbn-xsrf"] = "true"
        current = get_current_state(client, module)

        if state == "present":
            desired = build_payload(module, for_update=(current is not None))

            if current is None:
                # Resource does not exist - create it
                result["changed"] = True
                result["diff"]["before"] = {}
                result["diff"]["after"] = desired

                if not module.check_mode:
                    create_payload = build_payload(module, for_update=False)
                    response = client.post(
                        "/api/detection_engine/rules",
                        data=create_payload,
                    )
                    result.update(response if isinstance(response, dict) else {})

            elif needs_update(current, desired):
                # Resource exists but needs updating
                result["changed"] = True
                result["diff"]["before"] = current
                result["diff"]["after"] = dict(current, **{k: v for k, v in desired.items() if v is not None})

                if not module.check_mode:
                    update_payload = build_payload(module, for_update=True)
                    update_payload["id"] = current.get("id")
                    response = client.put(
                        "/api/detection_engine/rules",
                        data=update_payload,
                    )
                    result.update(response if isinstance(response, dict) else {})

            else:
                # Resource exists and is up-to-date
                result["id"] = current.get("id")
                result["name"] = current.get("name")

        elif state == "absent":
            if current is not None:
                result["changed"] = True
                result["diff"]["before"] = current
                result["diff"]["after"] = {}

                if not module.check_mode:
                    rule_id = module.params.get("rule_id") or current.get("id")
                    client.delete(
                        "/api/detection_engine/rules",
                        params={"id": rule_id},
                    )

    except ClientError as e:
        module.fail_json(msg=str(e), **result)

    module.exit_json(**result)


if __name__ == "__main__":
    main()
